### ISSUE TITLE
Show assignee in Tooltip

### ISSUE THREAD

**Issue by visomedia** [helmus/Jira-Hot-Linker#9]
Hello Helmus,

thanks for this wonderful save timing app.

But it would be wonderful if the actual assigned person, would be also shown in the tooltip - that is an very import information for me.

That would be grandios.

All the best,
Philipp

**Comment by helmus** [comment]
Hi @visomedia  Given that the primary use case of this issue is github, I'm not entirely sure showing the assignee makes a lot of sense. As that should always be the github author.
You are welcome to send a pr for this feature with an optional config if you need it.
It should be easy to add the new div to the status list here:
https://github.com/helmus/Jira-Hot-Linker/blob/861ce2c5592a64850470dfc74d83b823ad80b8a3/jira-plugin/resources/annotation.html#L5
And then add a checkbox to the options page here:
https://github.com/helmus/Jira-Hot-Linker/blob/861ce2c5592a64850470dfc74d83b823ad80b8a3/jira-plugin/options/options.jsx#L70

**Comment by helmus** [comment]
@visomedia  we now show the assignee avatar in the tooltip title in the latest version. Hope this helps !

**Comment by lrozenblyum** [comment]
Hello @helmus. Sorry for resurrecting an old issue, but we see the 'reporter' avatar in the tooltip title, not 'assignee'.
Is it as expected?
